include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  exclude:
    - build/**
    - example/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - camel_case_types