name: advanced_navigator
description: A Flutter Navigator which combines the capabilities of the new Declarative and the existing Imperative Navigator API into one easy-to-use widget.
version: 0.0.1
author: Lucas Aschenbach
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
